-- Seed data: recipes from nutrition database
-- Auto-generated from nutrition-export.json

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('porridge-mela-cannella', 'Porridge Proteico Mela e Cannella', 'workout', 'colazione', 'facile', 10, 'dolce', '{"veloce","pre-workout","proteico"}', '{"50g fiocchi d''avena","200ml latte (o bevanda vegetale)","1 mela tagliata a cubetti","1 cucchiaino cannella in polvere","15g mandorle spezzettate","1 cucchiaio miele"}', '{"Scalda il latte in un pentolino a fuoco medio","Aggiungi l''avena e cuoci mescolando per 5 minuti","Aggiungi i cubetti di mela e la cannella, mescola bene","Servi in una ciotola e guarnisci con mandorle e miele"}', 'Puoi preparare l''avena la sera prima con il metodo overnight oats (avena + latte in frigo)', 18, 52, 12, 380);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('toast-avocado-uova', 'Toast Avocado e Uova Strapazzate', 'workout', 'colazione', 'facile', 8, 'salato', '{"veloce","proteico","salato"}', '{"2 fette pane integrale (60g totali)","1 uovo intero + 100g albume","1/2 avocado maturo","Sale, pepe q.b.","1 cucchiaino olio d''oliva"}', '{"Tosta le fette di pane","Sbatti uovo e albume insieme, cuoci in padella antiaderente con poco olio","Schiaccia l''avocado con una forchetta, condisci con sale e pepe","Spalma l''avocado sul toast e aggiungi le uova strapazzate sopra"}', NULL, 25, 40, 14, 390);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('yogurt-greco-frutti-rossi', 'Yogurt Greco Bowl con Frutti Rossi e Granola', 'workout', 'colazione', 'facilissimo', 5, 'dolce', '{"velocissimo","freddo","proteico"}', '{"170g yogurt greco magro","40g granola (o cereali integrali)","80g frutti rossi misti (fragole, mirtilli, lamponi)","10 noci spezzettate","1 cucchiaino miele"}', '{"Versa lo yogurt greco in una bowl","Aggiungi la granola e i frutti rossi","Sbriciola le noci sopra","Finisci con un filo di miele"}', NULL, 20, 48, 10, 360);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pancake-proteici-avena', 'Pancake Proteici all''Avena', 'workout', 'colazione', 'media', 15, 'dolce', '{"proteico","dolce"}', '{"50g fiocchi d''avena tritati","1 uovo intero + 50g albume","100ml latte","1 cucchiaino lievito per dolci","Marmellata o miele per guarnire","15g mandorle"}', '{"Frulla l''avena fino a ottenere una farina grossolana","Mescola avena, uovo, albume, latte e lievito fino a ottenere un composto liscio","Cuoci i pancake in padella antiaderente (2-3 minuti per lato)","Servi con marmellata e mandorle"}', NULL, 22, 45, 12, 380);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('fette-biscottate-ricotta-miele', 'Fette Biscottate con Ricotta e Miele', 'workout', 'colazione', 'facilissimo', 5, 'dolce', '{"velocissimo","dolce"}', '{"40g fette biscottate integrali","100g ricotta magra","1 cucchiaio miele","15g noci tritate","Cannella in polvere"}', '{"Spalma la ricotta sulle fette biscottate","Aggiungi un filo di miele","Guarnisci con noci tritate e una spolverata di cannella"}', NULL, 18, 48, 11, 370);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('smoothie-bowl-frutti-rossi', 'Smoothie Bowl Energetico ai Frutti Rossi', 'workout', 'colazione', 'facile', 8, 'dolce', '{"veloce","freddo","energetico"}', '{"125g yogurt greco","100g frutti rossi surgelati","100ml latte","1 cucchiaio miele","30g granola","15g mandorle affettate"}', '{"Frulla yogurt, frutti rossi, latte e miele fino a ottenere una crema densa","Versa in una bowl","Guarnisci con granola e mandorle"}', NULL, 20, 50, 13, 400);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-burro-arachidi-miele', 'Pane Integrale con Burro di Arachidi e Miele', 'workout', 'colazione', 'facilissimo', 3, 'dolce', '{"velocissimo","energetico"}', '{"90g pane integrale (2 fette)","2 cucchiai burro di arachidi 100%","1 cucchiaio miele","Cannella in polvere (opzionale)"}', '{"Tosta leggermente il pane","Spalma il burro di arachidi","Aggiungi un filo di miele e una spolverata di cannella"}', NULL, 16, 52, 14, 400);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('gallette-salmone-avocado', 'Gallette con Salmone Affumicato e Avocado', 'workout', 'colazione', 'facile', 5, 'salato', '{"veloce","salato","proteico"}', '{"40g gallette di riso/mais","70g salmone affumicato","1/2 avocado","Succo di limone","Pepe nero"}', '{"Schiaccia l''avocado e condiscilo con limone e pepe","Spalma l''avocado sulle gallette","Adagia il salmone affumicato sopra"}', NULL, 22, 45, 15, 400);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('uova-pane-integrale', 'Uova Strapazzate su Pane Integrale', 'workout', 'colazione', 'facile', 10, 'salato', '{"proteico","salato"}', '{"1 uovo + 100g albume","90g pane integrale","1 cucchiaio olio d''oliva","Sale, pepe, erba cipollina","10g parmigiano grattugiato"}', '{"Sbatti uovo e albume con sale, pepe ed erba cipollina","Cuoci in padella con poco olio a fuoco medio-basso mescolando delicatamente","Tosta il pane","Servi le uova sul pane tostato, guarnisci con parmigiano"}', NULL, 28, 48, 12, 420);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('muesli-latte-frutta', 'Muesli con Latte e Frutta Fresca', 'workout', 'colazione', 'facilissimo', 3, 'dolce', '{"velocissimo","dolce"}', '{"50g muesli (o cereali integrali)","250ml latte (o bevanda vegetale)","1 mela a cubetti","15g mandorle","1 cucchiaino miele"}', '{"Versa il muesli in una ciotola","Aggiungi il latte","Guarnisci con cubetti di mela, mandorle e miele"}', NULL, 18, 55, 13, 410);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('toast-ricotta-miele-noci', 'Toast Ricotta, Miele e Noci', 'workout', 'colazione', 'facilissimo', 5, 'dolce', '{"veloce","dolce"}', '{"90g pane integrale","100g ricotta magra","1 cucchiaio miele","15g noci tritate","Cannella"}', '{"Tosta il pane","Spalma la ricotta","Aggiungi miele, noci e cannella"}', NULL, 20, 50, 14, 410);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('bresaola-pane-olio', 'Pane con Bresaola e Olio', 'workout', 'colazione', 'facilissimo', 3, 'salato', '{"velocissimo","salato","proteico"}', '{"90g pane integrale","90g bresaola (o fesa di tacchino)","1 cucchiaio olio d''oliva","Rucola fresca","Limone"}', '{"Taglia il pane a fette","Condisci con olio d''oliva","Aggiungi bresaola e rucola","Spruzza limone"}', NULL, 25, 48, 10, 390);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('mela-mandorle', 'Mela e Mandorle', 'workout', 'spuntino', 'facilissimo', 2, NULL, '{"velocissimo"}', '{"1 mela","10 mandorle"}', '{"Taglia la mela a spicchi","Accompagna con le mandorle"}', NULL, 3, 25, 6, 160);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('barretta-energetica', 'Barretta Energetica', 'workout', 'spuntino', 'facilissimo', 1, NULL, '{"velocissimo","pratico"}', '{"1 barretta energetica ai cereali"}', '{"Apri e mangia"}', NULL, 4, 30, 5, 180);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-miele', 'Fetta di Pane con Miele', 'workout', 'spuntino', 'facilissimo', 2, NULL, '{"velocissimo"}', '{"1 fetta pane (45g)","1 cucchiaio miele"}', '{"Spalma il miele sul pane"}', NULL, 3, 35, 1, 160);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frutta-secca-mix', 'Mix Frutta Secca', 'workout', 'spuntino', 'facilissimo', 1, NULL, '{"velocissimo"}', '{"10g mandorle","10g noci","10g nocciole"}', '{"Mescola e mangia"}', NULL, 5, 5, 18, 200);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('cracker-frutta', 'Cracker e Frutta', 'workout', 'spuntino', 'facilissimo', 2, NULL, '{"veloce"}', '{"20g cracker integrali","1 pera"}', '{"Accompagna i cracker con la pera"}', NULL, 3, 32, 3, 160);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('yogurt-magro', 'Yogurt Magro', 'workout', 'spuntino', 'facilissimo', 1, NULL, '{"velocissimo"}', '{"125g yogurt bianco magro","1 cucchiaino miele"}', '{"Mescola yogurt e miele"}', NULL, 5, 18, 1, 100);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('gallette-marmellata', 'Gallette con Marmellata', 'workout', 'spuntino', 'facilissimo', 2, NULL, '{"veloce"}', '{"20g gallette di riso","1 cucchiaio marmellata"}', '{"Spalma la marmellata sulle gallette"}', NULL, 2, 28, 1, 130);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('kiwi-noci', 'Kiwi e Noci', 'workout', 'spuntino', 'facilissimo', 2, NULL, '{"veloce","fresco"}', '{"2 kiwi","10 noci"}', '{"Sbuccia i kiwi","Accompagna con le noci"}', NULL, 3, 22, 9, 180);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('poke-bowl-salmone', 'Poke Bowl Salmone e Edamame', 'workout', 'pranzo', 'facile', 15, 'post-workout', '{"proteico","pesce","completo","meal-prep"}', '{"130g riso bianco (o precotto)","150g salmone fresco a cubetti","50g edamame","1/2 avocado","Cetriolo, carote julienne","Semi di sesamo","Salsa soia, olio sesamo"}', '{"Cuoci il riso (oppure usa precotto da supermercato)","Taglia il salmone a cubetti di 2cm","Componi la bowl: riso come base, aggiungi salmone, edamame, verdure e avocado","Guarnisci con sesamo e condisci con salsa soia e olio di sesamo"}', 'Puoi preparare il riso la sera prima. Comprabile pronto nei poke bar.', 38, 58, 20, 540);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pasta-pesto-pollo', 'Pasta al Pesto con Pollo Grigliato', 'workout', 'pranzo', 'facile', 20, 'post-workout', '{"proteico","italiano","meal-prep"}', '{"130g pasta (penne, fusilli)","150g petto di pollo","2 cucchiai pesto genovese","1 zucchina","Parmigiano grattugiato","Olio d''oliva"}', '{"Cuoci la pasta al dente","Taglia il pollo a strisce e griglialo in padella","Salta le zucchine a rondelle in padella","Scola la pasta, mescola con pesto, pollo e zucchine","Guarnisci con parmigiano"}', NULL, 42, 62, 18, 590);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('insalatona-caesar', 'Insalatona Caesar Proteica', 'workout', 'pranzo', 'facile', 10, 'post-workout', '{"proteico","fresco","veloce"}', '{"Lattuga romana 200g","150g pollo grigliato","40g crostini di pane","30g parmigiano a scaglie","Salsa caesar light","Olio d''oliva"}', '{"Lava e taglia la lattuga romana","Aggiungi il pollo tagliato a strisce","Aggiungi crostini e scaglie di parmigiano","Condisci con salsa caesar e olio"}', NULL, 38, 45, 16, 480);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('wrap-tacchino-hummus', 'Wrap Integrale Tacchino e Hummus', 'workout', 'pranzo', 'facilissimo', 8, 'post-workout', '{"proteico","velocissimo","pratico"}', '{"1 piadina integrale (100g)","100g fesa di tacchino","3 cucchiai hummus","Lattuga, pomodoro, cetriolo","Olio d''oliva"}', '{"Spalma l''hummus sulla piadina","Aggiungi tacchino e verdure fresche","Arrotola stretto","Taglia a metà"}', NULL, 32, 48, 14, 450);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('riso-venere-gamberetti', 'Riso Venere con Gamberetti e Zucchine', 'workout', 'pranzo', 'media', 25, 'post-workout', '{"proteico","gourmet","pesce","meal-prep"}', '{"130g riso venere","180g gamberetti sgusciati","2 zucchine","Aglio, prezzemolo","Olio d''oliva, limone"}', '{"Cuoci il riso venere (20 minuti)","Salta i gamberetti in padella con aglio","Aggiungi le zucchine a rondelle","Mescola con il riso, aggiungi limone e prezzemolo"}', NULL, 35, 60, 12, 500);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pasta-tonno-pomodorini', 'Pasta con Tonno e Pomodorini', 'workout', 'pranzo', 'facile', 15, 'post-workout', '{"proteico","veloce","italiano"}', '{"130g pasta","180g tonno al naturale","200g pomodorini","Aglio, basilico","Olio d''oliva"}', '{"Cuoci la pasta","Salta i pomodorini tagliati a metà con aglio e olio","Aggiungi il tonno sgocciolato","Mescola con la pasta e aggiungi basilico fresco"}', NULL, 40, 65, 15, 550);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('quinoa-pollo-verdure', 'Quinoa con Pollo e Verdure Grigliate', 'workout', 'pranzo', 'facile', 25, 'post-workout', '{"proteico","completo","meal-prep"}', '{"130g quinoa","150g petto di pollo","Zucchine, peperoni, melanzane","Olio d''oliva","Erbe aromatiche"}', '{"Cuoci la quinoa secondo istruzioni (15 min)","Griglia il pollo tagliato a cubetti","Griglia le verdure","Componi il piatto mescolando tutto, condisci con olio ed erbe"}', NULL, 42, 60, 18, 570);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('panino-bresaola-rucola', 'Panino Bresaola, Rucola e Grana', 'workout', 'pranzo', 'facilissimo', 5, 'post-workout', '{"velocissimo","pratico"}', '{"100g pane integrale","100g bresaola","Rucola fresca","30g grana a scaglie","Olio d''oliva, limone"}', '{"Taglia il pane a metà","Condisci l''interno con olio e limone","Aggiungi bresaola, rucola e grana","Chiudi il panino"}', NULL, 35, 50, 14, 470);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('riso-pollo-curry', 'Riso con Pollo al Curry', 'workout', 'pranzo', 'facile', 25, 'post-workout', '{"proteico","speziato","meal-prep"}', '{"130g riso basmati","150g petto di pollo","100ml latte di cocco light","1 cucchiaio curry in polvere","Cipolla, zucchine","Olio d''oliva"}', '{"Cuoci il riso basmati","Salta cipolla e pollo a cubetti in padella","Aggiungi curry e latte di cocco, cuoci 10 minuti","Aggiungi zucchine, servi con il riso"}', NULL, 38, 62, 16, 540);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pasta-salmone-zucchine', 'Pasta con Salmone e Zucchine', 'workout', 'pranzo', 'facile', 20, 'post-workout', '{"proteico","pesce"}', '{"130g pasta","120g salmone fresco","2 zucchine","Limone, aneto","Olio d''oliva"}', '{"Cuoci la pasta","Taglia il salmone a cubetti e cuoci in padella 4-5 minuti","Salta le zucchine a rondelle","Mescola pasta, salmone e zucchine, aggiungi limone e aneto"}', NULL, 35, 62, 18, 550);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('insalata-riso-tonno', 'Insalata di Riso con Tonno', 'workout', 'pranzo', 'facile', 15, 'post-workout', '{"fresco","meal-prep"}', '{"130g riso","180g tonno al naturale","Pomodorini, cetrioli, olive","Basilico","Olio d''oliva"}', '{"Cuoci il riso e fallo raffreddare","Taglia pomodorini e cetrioli","Mescola riso, tonno, verdure e olive","Condisci con olio e basilico fresco"}', NULL, 38, 60, 16, 530);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('couscous-pollo-verdure', 'Couscous con Pollo e Verdure', 'workout', 'pranzo', 'facile', 15, 'post-workout', '{"veloce","completo"}', '{"130g couscous","150g petto di pollo","Peperoni, zucchine","Spezie (paprika, cumino)","Olio d''oliva"}', '{"Prepara il couscous con acqua bollente (5 minuti)","Taglia pollo a cubetti e cuoci con le spezie","Salta le verdure","Mescola couscous, pollo e verdure"}', NULL, 40, 58, 14, 520);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('bowl-farro-tacchino', 'Bowl di Farro con Tacchino e Hummus', 'workout', 'pranzo', 'facile', 25, 'post-workout', '{"proteico","completo","meal-prep"}', '{"130g farro","150g fesa di tacchino a cubetti","3 cucchiai hummus","Pomodorini, cetrioli, rucola","Olio d''oliva"}', '{"Cuoci il farro (20 minuti)","Griglia il tacchino a cubetti","Componi la bowl: farro, tacchino, verdure, hummus","Condisci con olio"}', NULL, 38, 62, 16, 540);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pasta-broccoli-acciughe', 'Pasta con Broccoli e Acciughe', 'workout', 'pranzo', 'facile', 20, 'post-workout', '{"italiano","proteico"}', '{"130g pasta","200g broccoli","6 filetti di acciughe","Aglio, peperoncino","Olio d''oliva","Parmigiano"}', '{"Cuoci i broccoli a vapore o lessali","Cuoci la pasta","Salta aglio, acciughe e peperoncino in olio","Aggiungi broccoli, schiaccia leggermente, mescola con la pasta","Guarnisci con parmigiano"}', NULL, 28, 65, 18, 530);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('riso-pollo-verdure-salsa-soia', 'Riso alla Cantonese con Pollo', 'workout', 'pranzo', 'facile', 20, 'post-workout', '{"veloce","completo"}', '{"130g riso","150g petto di pollo","1 uovo","Piselli, carote","Salsa di soia","Olio di sesamo"}', '{"Cuoci il riso e fallo raffreddare (meglio se avanzato)","Taglia il pollo a cubetti e cuocilo in padella","Sbatti l''uovo e fai una frittata, tagliala a striscioline","In un wok, salta riso, pollo, verdure, uovo","Condisci con salsa di soia e olio di sesamo"}', NULL, 42, 60, 16, 560);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('orzo-verdure-feta', 'Insalata di Orzo con Verdure e Feta', 'workout', 'pranzo', 'facile', 20, 'post-workout', '{"fresco","vegetariano","meal-prep"}', '{"130g orzo perlato","125g feta a cubetti","Pomodorini, cetrioli, olive","Basilico, origano","Olio d''oliva"}', '{"Cuoci l''orzo e fallo raffreddare","Taglia verdure e feta a cubetti","Mescola orzo, verdure, feta e olive","Condisci con olio, basilico e origano"}', NULL, 22, 62, 18, 500);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('piadina-pollo-verdure', 'Piadina con Pollo Grigliato e Verdure', 'workout', 'pranzo', 'facile', 15, 'post-workout', '{"veloce","pratico"}', '{"1 piadina (120g)","150g pollo grigliato","Insalata, pomodori","Maionese light o yogurt greco","Olio d''oliva"}', '{"Scalda leggermente la piadina","Aggiungi pollo a strisce","Aggiungi verdure fresche","Condisci con maionese light o yogurt greco","Arrotola e taglia a metà"}', NULL, 40, 55, 16, 530);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('burger-tacchino-patate', 'Burger di Tacchino con Patate al Forno', 'workout', 'pranzo', 'media', 30, 'post-workout', '{"proteico","completo"}', '{"150g macinato di tacchino","1 panino integrale (90g)","150g patate","Insalata, pomodoro","Senape, ketchup","Olio d''oliva"}', '{"Forma un burger con il tacchino macinato, cuoci in padella","Taglia le patate a spicchi, condisci con olio e cuoci al forno 200°C per 25 minuti","Tosta il panino","Componi il burger con verdure e salse","Servi con le patate"}', NULL, 38, 62, 16, 550);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('yogurt-cocco', 'Yogurt Greco con Cocco Disidratato', 'workout', 'merenda', 'facilissimo', 2, NULL, '{"velocissimo"}', '{"125g yogurt greco magro","20g cocco disidratato"}', '{"Mescola yogurt e cocco"}', NULL, 12, 18, 8, 190);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frutta-mandorle', 'Frutta Fresca e Mandorle', 'workout', 'merenda', 'facilissimo', 2, NULL, '{"veloce"}', '{"1 frutto (mela, pera, arancia)","15g mandorle"}', '{"Accompagna la frutta con le mandorle"}', NULL, 4, 22, 9, 180);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('barretta-proteica', 'Barretta Proteica', 'workout', 'merenda', 'facilissimo', 1, NULL, '{"velocissimo","pratico"}', '{"1 barretta proteica"}', '{"Apri e mangia"}', NULL, 20, 20, 8, 230);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('crackers-hummus', 'Crackers con Hummus', 'workout', 'merenda', 'facilissimo', 3, NULL, '{"veloce"}', '{"30g crackers integrali","3 cucchiai hummus"}', '{"Spalma l''hummus sui crackers"}', NULL, 6, 25, 8, 190);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frullato-proteico', 'Frullato Proteico', 'workout', 'merenda', 'facile', 5, NULL, '{"veloce","proteico"}', '{"20g proteine in polvere","200ml latte","1 frutto"}', '{"Frulla tutti gli ingredienti"}', NULL, 25, 20, 3, 210);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-cioccolato', 'Fetta di Pane con Cioccolato Fondente', 'workout', 'merenda', 'facilissimo', 2, NULL, '{"veloce","dolce"}', '{"45g pane integrale","20g cioccolato fondente 85%"}', '{"Sciogli leggermente il cioccolato e spalma sul pane"}', NULL, 4, 28, 8, 200);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('ricotta-miele', 'Ricotta con Miele', 'workout', 'merenda', 'facilissimo', 2, NULL, '{"veloce","proteico"}', '{"100g ricotta magra","1 cucchiaio miele","Cannella"}', '{"Mescola ricotta, miele e cannella"}', NULL, 11, 16, 5, 150);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('smoothie-frutti-rossi', 'Smoothie ai Frutti Rossi', 'workout', 'merenda', 'facile', 5, NULL, '{"veloce","fresco"}', '{"100g frutti rossi misti","125g yogurt greco","100ml latte"}', '{"Frulla tutti gli ingredienti"}', NULL, 12, 22, 3, 160);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('toast-burro-arachidi', 'Toast con Burro di Arachidi', 'workout', 'merenda', 'facilissimo', 3, NULL, '{"veloce"}', '{"1 fetta pane (45g)","1 cucchiaio burro arachidi 100%"}', '{"Tosta il pane","Spalma il burro di arachidi"}', NULL, 6, 22, 8, 180);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('noci-frutta-secca', 'Mix Noci e Frutta Secca', 'workout', 'merenda', 'facilissimo', 1, NULL, '{"velocissimo"}', '{"15g noci","15g uvetta"}', '{"Mescola e mangia"}', NULL, 3, 18, 10, 170);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pesce-verdure', 'Pesce al Forno con Verdure', 'workout', 'cena', 'facile', 30, NULL, '{"proteico","leggero","pesce"}', '{"200g pesce magro (merluzzo, orata, branzino)","60g pane integrale","Verdure miste (zucchine, pomodorini, peperoni)","Limone, erbe aromatiche","Olio d''oliva"}', '{"Condisci il pesce con limone, sale, pepe ed erbe","Taglia le verdure","Disponi pesce e verdure in teglia, condisci con olio","Inforna a 180°C per 20-25 minuti","Servi con pane integrale"}', NULL, 40, 30, 18, 440);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pollo-patate-verdure', 'Petto di Pollo con Patate al Forno', 'workout', 'cena', 'facile', 35, NULL, '{"proteico","completo"}', '{"200g petto di pollo","150g patate","Verdure grigliate (zucchine, melanzane)","Rosmarino, aglio","Olio d''oliva"}', '{"Taglia le patate a spicchi, condisci con olio, rosmarino e aglio","Inforna le patate a 200°C per 15 minuti","Griglia il pollo in padella 6-7 minuti per lato","Griglia le verdure","Servi insieme"}', NULL, 42, 35, 16, 460);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frittata-spinaci-ricotta', 'Frittata di Albumi con Spinaci e Ricotta', 'workout', 'cena', 'facile', 15, NULL, '{"proteico","veloce","vegetariano"}', '{"2 uova + 150g albume","100g spinaci freschi","50g ricotta magra","Parmigiano grattugiato","Insalata mista","Olio d''oliva"}', '{"Salta gli spinaci in padella","Sbatti uova e albume, aggiungi spinaci e ricotta","Versa in padella antiaderente, cuoci 8-10 minuti a fuoco basso","Guarnisci con parmigiano","Servi con insalata mista"}', NULL, 40, 8, 16, 340);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('salmone-insalata', 'Salmone Grigliato con Insalata', 'workout', 'cena', 'facile', 15, NULL, '{"proteico","leggero","pesce"}', '{"200g salmone","Insalata mista abbondante","60g pane integrale","Limone, aneto","Olio d''oliva"}', '{"Griglia il salmone 4-5 minuti per lato","Condisci con limone e aneto","Prepara l''insalata mista","Servi insieme al pane"}', NULL, 45, 32, 20, 490);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('tacchino-verdure-grigliate', 'Tacchino ai Ferri con Verdure Grigliate', 'workout', 'cena', 'facile', 20, NULL, '{"proteico","leggero"}', '{"200g fesa di tacchino","Zucchine, peperoni, melanzane","60g pane integrale","Erbe aromatiche","Olio d''oliva"}', '{"Griglia il tacchino in padella o piastra","Griglia le verdure tagliate a fette","Condisci con olio ed erbe aromatiche","Servi con pane integrale"}', NULL, 45, 34, 14, 450);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('vellutata-vitello', 'Vellutata di Verdure con Vitello', 'workout', 'cena', 'media', 35, NULL, '{"comfort","completo"}', '{"200g vitello magro","200g zucca","150g patate","Carote, sedano","Brodo vegetale","Olio d''oliva"}', '{"Taglia verdure a cubetti, cuoci in brodo 20 minuti","Frulla fino a ottenere una vellutata","Cuoci il vitello in padella","Servi la vellutata con il vitello"}', NULL, 44, 32, 16, 460);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('omelette-verdure', 'Omelette con Verdure e Formaggio', 'workout', 'cena', 'facile', 12, NULL, '{"veloce","proteico"}', '{"2 uova + 100g albume","Zucchine, peperoni","30g formaggio light","Insalata","Olio d''oliva"}', '{"Salta le verdure in padella","Sbatti uova e albume, versa in padella","Aggiungi verdure e formaggio, piega a metà","Servi con insalata"}', NULL, 38, 12, 18, 370);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('branzino-forno', 'Branzino al Forno con Patate', 'workout', 'cena', 'media', 40, NULL, '{"pesce","completo"}', '{"250g branzino","200g patate","Limone, rosmarino","Verdure di contorno","Olio d''oliva"}', '{"Pulisci il branzino, condisci con limone e rosmarino","Taglia le patate a spicchi","Disponi in teglia branzino e patate, condisci con olio","Inforna a 180°C per 30 minuti","Servi con verdure"}', NULL, 48, 38, 16, 500);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('burger-pollo-insalata', 'Burger di Pollo con Insalata', 'workout', 'cena', 'facile', 20, NULL, '{"proteico","veloce"}', '{"150g macinato di pollo","1 panino integrale (60g)","Insalata, pomodoro","Senape, yogurt greco","Olio d''oliva"}', '{"Forma un burger con il pollo macinato","Cuoci in padella 5-6 minuti per lato","Tosta il panino","Componi con verdure e salse"}', NULL, 40, 32, 14, 420);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('tonno-fagioli-insalata', 'Tonno con Insalata Mista', 'workout', 'cena', 'facilissimo', 10, NULL, '{"velocissimo","leggero"}', '{"200g tonno al naturale","Insalata mista abbondante","Pomodorini, cetrioli","60g pane integrale","Olio d''oliva, limone"}', '{"Prepara l''insalata con verdure fresche","Sgocciola il tonno e aggiungi all''insalata","Condisci con olio e limone","Servi con pane"}', NULL, 42, 30, 15, 430);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('polpette-tacchino-zucchine', 'Polpette di Tacchino con Zucchine', 'workout', 'cena', 'media', 30, NULL, '{"proteico"}', '{"200g macinato tacchino","1 uovo","Pangrattato, parmigiano","3 zucchine","Salsa di pomodoro","Olio d''oliva"}', '{"Impasta tacchino, uovo, pangrattato e parmigiano","Forma polpette e cuoci in padella","Taglia zucchine a spaghetti o rondelle, salta in padella","Aggiungi salsa di pomodoro","Servi polpette con zucchine"}', NULL, 46, 18, 18, 430);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('merluzzo-vapore-verdure', 'Merluzzo al Vapore con Verdure', 'workout', 'cena', 'facile', 25, NULL, '{"leggero","pesce"}', '{"250g merluzzo","Broccoli, carote, fagiolini","60g pane integrale","Limone, prezzemolo","Olio d''oliva"}', '{"Cuoci il merluzzo al vapore 12-15 minuti","Cuoci le verdure al vapore","Condisci pesce e verdure con olio, limone e prezzemolo","Servi con pane"}', NULL, 48, 32, 12, 440);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('petto-pollo-limone', 'Petto di Pollo al Limone con Insalata', 'workout', 'cena', 'facile', 20, NULL, '{"veloce","leggero"}', '{"200g petto di pollo","Limone, timo","Insalata mista","60g pane integrale","Olio d''oliva"}', '{"Marina il pollo con limone e timo 10 minuti","Cuoci in padella 6-7 minuti per lato","Prepara insalata mista","Servi insieme al pane"}', NULL, 44, 32, 14, 440);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('uova-verdure', 'Uova al Tegamino con Verdure', 'workout', 'cena', 'facile', 15, NULL, '{"veloce","proteico"}', '{"2 uova + 150g albume","Spinaci, pomodorini","60g pane integrale","Parmigiano","Olio d''oliva"}', '{"Salta spinaci e pomodorini in padella","Crea spazi nella padella e aggiungi uova e albume","Cuoci fino a quando l''albume è rappreso","Guarnisci con parmigiano","Servi con pane"}', NULL, 42, 34, 16, 460);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('sogliola-griglia-verdure', 'Sogliola alla Griglia con Verdure', 'workout', 'cena', 'facile', 20, NULL, '{"pesce","leggero"}', '{"250g sogliola","Zucchine, melanzane grigliate","60g pane integrale","Limone, prezzemolo","Olio d''oliva"}', '{"Griglia la sogliola 4-5 minuti per lato","Griglia le verdure","Condisci con limone, prezzemolo e olio","Servi con pane"}', NULL, 46, 32, 14, 450);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('latte-pane-marmellata', 'Latte con Pane Integrale e Marmellata', 'rest', 'colazione', 'facilissimo', 5, 'dolce', '{"veloce","dolce"}', '{"250ml latte (o bevanda vegetale)","90g pane integrale","2 cucchiai marmellata","20 mandorle"}', '{"Scalda il latte","Tosta leggermente il pane","Spalma la marmellata sul pane","Accompagna con le mandorle"}', NULL, 20, 65, 15, 480);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('yogurt-cereali-noci', 'Yogurt con Cereali e Noci', 'rest', 'colazione', 'facilissimo', 3, 'dolce', '{"velocissimo","dolce"}', '{"125g yogurt bianco magro","50g cereali integrali","10 noci tritate"}', '{"Versa lo yogurt in una bowl","Aggiungi cereali e noci","Mescola"}', NULL, 18, 55, 12, 400);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-bresaola-olio', 'Pane Integrale con Bresaola e Olio', 'rest', 'colazione', 'facilissimo', 5, 'salato', '{"veloce","salato","proteico"}', '{"90g pane integrale","90g bresaola (o fesa tacchino)","1 cucchiaio olio d''oliva","Rucola"}', '{"Condisci il pane con olio","Aggiungi bresaola e rucola"}', NULL, 25, 50, 10, 410);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('gallette-ricotta-miele-noci', 'Gallette con Ricotta, Miele e Noci', 'rest', 'colazione', 'facilissimo', 5, 'dolce', '{"veloce","dolce"}', '{"40g gallette di riso","100g ricotta magra","1 cucchiaio miele","15g noci"}', '{"Spalma la ricotta sulle gallette","Aggiungi miele e noci tritate"}', NULL, 20, 48, 14, 400);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('cappuccino-fette-biscottate', 'Cappuccino con Fette Biscottate', 'rest', 'colazione', 'facilissimo', 5, 'dolce', '{"veloce","dolce"}', '{"200ml latte per cappuccino","Caffe","40g fette biscottate","Marmellata","15g mandorle"}', '{"Prepara il cappuccino","Spalma marmellata sulle fette biscottate","Accompagna con mandorle"}', NULL, 16, 52, 12, 380);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pancake-proteici-riposo', 'Pancake Proteici con Frutta', 'rest', 'colazione', 'media', 15, 'dolce', '{"proteico","dolce"}', '{"120g mix pancake proteici","Miele o marmellata","Frutti rossi","15g noci"}', '{"Prepara i pancake secondo istruzioni","Guarnisci con miele e frutti rossi","Aggiungi noci"}', NULL, 25, 50, 14, 430);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-uova-salmone', 'Pane con Uova e Salmone Affumicato', 'rest', 'colazione', 'facile', 10, 'salato', '{"proteico","salato","gourmet"}', '{"60g pane integrale","1 uovo + 100g albume","70g salmone affumicato","Erba cipollina"}', '{"Tosta il pane","Prepara uova strapazzate","Adagia salmone e uova sul pane","Guarnisci con erba cipollina"}', NULL, 32, 42, 16, 450);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('porridge-mirtilli', 'Porridge con Mirtilli e Mandorle', 'rest', 'colazione', 'facile', 10, 'dolce', '{"dolce","energetico"}', '{"50g avena","200ml latte","80g mirtilli","20g mandorle","Miele"}', '{"Cuoci avena nel latte 5-7 minuti","Aggiungi mirtilli","Guarnisci con mandorle e miele"}', NULL, 18, 58, 14, 430);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('toast-avocado-uova-riposo', 'Toast Avocado e Uova', 'rest', 'colazione', 'facile', 10, 'salato', '{"salato","proteico"}', '{"90g pane integrale","1/2 avocado","1 uovo + 50g albume","Sale, pepe, limone"}', '{"Tosta il pane","Schiaccia avocado con limone","Prepara uova strapazzate o al tegamino","Componi il toast"}', NULL, 22, 52, 16, 450);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('smoothie-bowl-riposo', 'Smoothie Bowl Completo', 'rest', 'colazione', 'facile', 10, 'dolce', '{"dolce","fresco"}', '{"170g yogurt greco","100g frutti rossi","30g granola","15g mandorle","Miele"}', '{"Frulla yogurt e metà dei frutti rossi","Versa in bowl","Guarnisci con granola, mandorle, frutti rossi e miele"}', NULL, 22, 54, 14, 430);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-hummus-verdure', 'Pane con Hummus e Verdure', 'rest', 'colazione', 'facilissimo', 5, 'salato', '{"veloce","salato","vegetariano"}', '{"90g pane integrale","4 cucchiai hummus","Pomodori, cetrioli","Rucola"}', '{"Tosta il pane","Spalma hummus","Aggiungi verdure fresche"}', NULL, 16, 56, 12, 400);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('muesli-yogurt-frutta', 'Muesli con Yogurt e Frutta', 'rest', 'colazione', 'facilissimo', 3, 'dolce', '{"velocissimo","dolce"}', '{"50g muesli","170g yogurt greco","1 mela a cubetti","10 noci"}', '{"Mescola muesli e yogurt","Aggiungi mela e noci"}', NULL, 20, 60, 13, 440);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('cornflakes-latte-frutta', 'Cornflakes con Latte e Frutta', 'rest', 'colazione', 'facilissimo', 3, 'dolce', '{"velocissimo","dolce"}', '{"50g cornflakes semplici","250ml latte","1 kiwi a fette","15g mandorle"}', '{"Versa cornflakes e latte in una bowl","Aggiungi kiwi e mandorle"}', NULL, 18, 58, 14, 430);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('toast-ricotta-miele-riposo', 'Toast con Ricotta e Miele', 'rest', 'colazione', 'facilissimo', 5, 'dolce', '{"veloce","dolce"}', '{"90g pane integrale","100g ricotta magra","2 cucchiai miele","15g noci","Cannella"}', '{"Tosta il pane","Spalma ricotta","Aggiungi miele, noci e cannella"}', NULL, 22, 60, 15, 470);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('cracker-frutta-riposo', 'Cracker e Frutta', 'rest', 'spuntino', 'facilissimo', 2, NULL, '{"veloce"}', '{"40g cracker integrali","1 mela"}', '{"Accompagna i cracker con la frutta"}', NULL, 4, 38, 4, 200);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('gallette-frutta', 'Gallette e Frutta', 'rest', 'spuntino', 'facilissimo', 2, NULL, '{"veloce"}', '{"40g gallette di riso","1 pera"}', '{"Accompagna le gallette con la frutta"}', NULL, 3, 40, 2, 190);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('parmigiano-verdure', 'Parmigiano e Verdure Crude', 'rest', 'spuntino', 'facilissimo', 3, NULL, '{"veloce","proteico"}', '{"20g parmigiano a cubetti","Finocchi, carote, sedano"}', '{"Taglia verdure a bastoncini","Accompagna con parmigiano"}', NULL, 8, 6, 6, 110);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('cioccolato-fondente-frutta', 'Cioccolato Fondente e Frutta', 'rest', 'spuntino', 'facilissimo', 2, NULL, '{"veloce","dolce"}', '{"30g cioccolato fondente 85%","1 arancia"}', '{"Accompagna il cioccolato con l''arancia"}', NULL, 3, 28, 12, 230);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frutta-guscio-frutta-riposo', 'Frutta a Guscio e Frutta Fresca', 'rest', 'spuntino', 'facilissimo', 1, NULL, '{"velocissimo"}', '{"10g mandorle o noci","1 kiwi"}', '{"Accompagna frutta secca con frutta fresca"}', NULL, 3, 18, 6, 130);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('yogurt-cocco-riposo', 'Yogurt con Cocco', 'rest', 'spuntino', 'facilissimo', 2, NULL, '{"veloce"}', '{"125g yogurt magro","20g cocco disidratato"}', '{"Mescola yogurt e cocco"}', NULL, 5, 20, 8, 170);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('verdure-crude-pinzimonio', 'Verdure Crude in Pinzimonio', 'rest', 'spuntino', 'facilissimo', 5, NULL, '{"veloce","leggero"}', '{"Finocchi, carote, sedano, peperoni","Olio, sale"}', '{"Taglia verdure a bastoncini","Prepara pinzimonio con olio e sale"}', NULL, 2, 8, 5, 80);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('lupini-verdure', 'Lupini e Verdure Crude', 'rest', 'spuntino', 'facilissimo', 2, NULL, '{"veloce","proteico"}', '{"90g lupini","Finocchi, carote"}', '{"Accompagna lupini con verdure"}', NULL, 10, 8, 2, 90);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('barretta-proteica-riposo', 'Barretta Proteica', 'rest', 'spuntino', 'facilissimo', 1, NULL, '{"velocissimo"}', '{"1 barretta proteica"}', '{"Apri e mangia"}', NULL, 20, 20, 8, 230);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pizza-farcita', 'Trancio di Pizza Farcita', 'rest', 'spuntino', 'facilissimo', 2, NULL, '{"veloce"}', '{"130g pizza farcita (verdure, prosciutto)"}', '{"Scalda e mangia"}', NULL, 12, 45, 10, 320);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-affettato', 'Panino con Affettato Magro', 'rest', 'spuntino', 'facilissimo', 3, NULL, '{"veloce","proteico"}', '{"60g pane","50g bresaola o fesa tacchino"}', '{"Componi il panino"}', NULL, 18, 32, 4, 240);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frutta-secca-uvetta', 'Mix Frutta Secca e Uvetta', 'rest', 'spuntino', 'facilissimo', 1, NULL, '{"velocissimo"}', '{"10g mandorle","10g noci","20g uvetta"}', '{"Mescola e mangia"}', NULL, 3, 22, 8, 170);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pasta-tonno-verdure', 'Pasta con Tonno e Verdure', 'rest', 'pranzo', 'facile', 15, NULL, '{"veloce","completo"}', '{"130g pasta","180g tonno al naturale","Verdure miste (zucchine, pomodorini)","20g olio d''oliva"}', '{"Cuoci la pasta","Salta le verdure in padella","Aggiungi tonno sgocciolato","Mescola con la pasta e condisci con olio"}', NULL, 40, 65, 20, 590);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('riso-legumi-verdure', 'Riso e Hummus con Verdure', 'rest', 'pranzo', 'facile', 20, NULL, '{"vegetariano","completo"}', '{"130g riso","4 cucchiai hummus","Verdure miste grigliate","20g olio d''oliva"}', '{"Cuoci il riso","Griglia le verdure","Servi riso con hummus e verdure","Condisci con olio"}', NULL, 14, 70, 20, 520);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('quinoa-pollo-verdure-riposo', 'Quinoa con Pollo e Verdure', 'rest', 'pranzo', 'facile', 25, NULL, '{"completo","proteico"}', '{"130g quinoa","150g pollo","Verdure miste","20g olio"}', '{"Cuoci quinoa","Griglia pollo","Griglia verdure","Componi il piatto"}', NULL, 42, 60, 20, 580);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-tacchino-finocchi', 'Pane con Fesa di Tacchino e Finocchi', 'rest', 'pranzo', 'facilissimo', 5, NULL, '{"velocissimo","proteico"}', '{"90g pane integrale","100g fesa tacchino","Finocchi freschi","20g olio"}', '{"Componi panino con tacchino","Accompagna con finocchi","Condisci con olio"}', NULL, 28, 50, 15, 460);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('insalata-riso-pollo', 'Insalata di Riso con Pollo', 'rest', 'pranzo', 'facile', 20, NULL, '{"fresco","completo"}', '{"130g riso","150g pollo","Verdure miste (pomodori, cetrioli, olive)","20g olio"}', '{"Cuoci riso e fallo raffreddare","Griglia pollo e taglialo a cubetti","Mescola riso, pollo e verdure","Condisci con olio"}', NULL, 40, 62, 20, 580);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pasta-verdure-parmigiano', 'Pasta con Verdure e Parmigiano', 'rest', 'pranzo', 'facile', 15, NULL, '{"vegetariano","veloce"}', '{"130g pasta","50g parmigiano grattugiato","Verdure miste (zucchine, pomodorini)","20g olio"}', '{"Cuoci pasta","Salta verdure","Mescola con parmigiano e olio"}', NULL, 26, 65, 22, 550);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('piadina-pollo-verdure-riposo', 'Piadina con Pollo e Verdure', 'rest', 'pranzo', 'facile', 15, NULL, '{"veloce","pratico"}', '{"1 piadina (120g)","150g pollo grigliato","Insalata, pomodori","Yogurt greco o hummus"}', '{"Scalda piadina","Aggiungi pollo e verdure","Condisci con yogurt o hummus","Arrotola"}', NULL, 38, 58, 18, 540);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('focaccia-verdure-mozzarella', 'Focaccia con Verdure e Mozzarella', 'rest', 'pranzo', 'facile', 10, NULL, '{"veloce","vegetariano"}', '{"200g focaccia","125g mozzarella magra","Verdure grigliate","Olio"}', '{"Taglia focaccia a metà","Farcisci con mozzarella e verdure","Scalda leggermente"}', NULL, 30, 70, 22, 600);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pasta-salmone-affumicato', 'Pasta con Salmone Affumicato', 'rest', 'pranzo', 'facile', 15, NULL, '{"veloce","pesce"}', '{"130g pasta","100g salmone affumicato","Panna light o yogurt greco","Erba cipollina","Olio"}', '{"Cuoci pasta","Prepara salsa con yogurt ed erba cipollina","Aggiungi salmone a pezzetti","Mescola con la pasta"}', NULL, 32, 62, 18, 530);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('riso-pesce-verdure', 'Riso con Pesce e Verdure', 'rest', 'pranzo', 'media', 25, NULL, '{"completo","pesce"}', '{"130g riso","150g pesce magro","Verdure miste","20g olio"}', '{"Cuoci riso","Cuoci pesce al vapore o in padella","Salta verdure","Servi insieme"}', NULL, 38, 62, 20, 560);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('bowl-farro-verdure-feta', 'Bowl di Farro con Verdure e Feta', 'rest', 'pranzo', 'facile', 25, NULL, '{"completo","vegetariano"}', '{"130g farro","125g feta","Verdure grigliate","20g olio","Olive"}', '{"Cuoci farro","Griglia verdure","Componi bowl con farro, verdure, feta e olive","Condisci con olio"}', NULL, 28, 60, 24, 560);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('panino-tonno-verdure', 'Panino con Tonno e Verdure', 'rest', 'pranzo', 'facilissimo', 5, NULL, '{"velocissimo"}', '{"90g pane","180g tonno al naturale","Insalata, pomodori","Olio"}', '{"Componi panino con tonno e verdure","Condisci con olio"}', NULL, 38, 50, 15, 490);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('couscous-verdure-hummus', 'Couscous con Verdure e Hummus', 'rest', 'pranzo', 'facile', 15, NULL, '{"veloce","vegetariano"}', '{"130g couscous","4 cucchiai hummus","Verdure grigliate","20g olio"}', '{"Prepara couscous","Griglia verdure","Servi con hummus","Condisci con olio"}', NULL, 16, 68, 22, 530);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('patate-pesce-verdure', 'Patate al Forno con Pesce', 'rest', 'pranzo', 'media', 35, NULL, '{"completo","pesce"}', '{"300g patate","150g pesce magro","Verdure","20g olio"}', '{"Cuoci patate al forno","Cuoci pesce","Prepara verdure","Servi insieme"}', NULL, 35, 58, 20, 540);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('insalata-pollo-avocado', 'Insalatona con Pollo e Avocado', 'rest', 'pranzo', 'facile', 15, NULL, '{"fresco","proteico"}', '{"150g pollo grigliato","1 avocado","Insalata mista abbondante","40g pane","Olio, limone"}', '{"Taglia pollo a strisce","Taglia avocado a cubetti","Componi insalata","Condisci con olio e limone","Accompagna con pane"}', NULL, 38, 42, 24, 540);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pasta-ricotta-verdure', 'Pasta con Ricotta e Verdure', 'rest', 'pranzo', 'facile', 15, NULL, '{"veloce","vegetariano"}', '{"130g pasta","100g ricotta magra","Spinaci o zucchine","Parmigiano","Olio"}', '{"Cuoci pasta","Salta verdure","Mescola pasta, ricotta e verdure","Guarnisci con parmigiano"}', NULL, 26, 64, 18, 520);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('yogurt-cocco-pom', 'Yogurt con Cocco', 'rest', 'merenda', 'facilissimo', 2, NULL, '{"veloce"}', '{"125g yogurt magro","20g cocco disidratato"}', '{"Mescola yogurt e cocco"}', NULL, 5, 20, 8, 170);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frutta-noci-pom', 'Frutta e Noci', 'rest', 'merenda', 'facilissimo', 2, NULL, '{"veloce"}', '{"10g noci","1 frutto"}', '{"Accompagna frutta con noci"}', NULL, 3, 20, 6, 140);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('lupini-verdure-pom', 'Lupini con Verdure', 'rest', 'merenda', 'facilissimo', 2, NULL, '{"proteico"}', '{"90g lupini","Verdure crude"}', '{"Accompagna lupini con verdure"}', NULL, 10, 8, 2, 90);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pizza-farcita-pom', 'Trancio Pizza', 'rest', 'merenda', 'facilissimo', 2, NULL, '{"veloce"}', '{"130g pizza farcita"}', '{"Scalda e mangia"}', NULL, 12, 45, 10, 320);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('barretta-pom', 'Barretta Proteica', 'rest', 'merenda', 'facilissimo', 1, NULL, '{"velocissimo"}', '{"1 barretta proteica"}', '{"Apri e mangia"}', NULL, 20, 20, 8, 230);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('crackers-formaggio', 'Crackers con Formaggio', 'rest', 'merenda', 'facilissimo', 3, NULL, '{"veloce"}', '{"30g crackers","30g formaggio magro"}', '{"Accompagna crackers con formaggio"}', NULL, 10, 22, 8, 200);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frutta-cioccolato-pom', 'Frutta e Cioccolato', 'rest', 'merenda', 'facilissimo', 2, NULL, '{"dolce"}', '{"1 frutto","20g cioccolato fondente"}', '{"Accompagna frutta con cioccolato"}', NULL, 2, 28, 8, 190);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pane-marmellata-pom', 'Pane con Marmellata', 'rest', 'merenda', 'facilissimo', 3, NULL, '{"veloce","dolce"}', '{"45g pane","2 cucchiai marmellata"}', '{"Spalma marmellata sul pane"}', NULL, 3, 38, 2, 180);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('smoothie-pom', 'Smoothie Frutta e Yogurt', 'rest', 'merenda', 'facile', 5, NULL, '{"fresco"}', '{"125g yogurt","100g frutta mista","Latte"}', '{"Frulla tutti gli ingredienti"}', NULL, 8, 25, 3, 160);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('toast-hummus-pom', 'Toast con Hummus', 'rest', 'merenda', 'facilissimo', 3, NULL, '{"veloce"}', '{"45g pane","3 cucchiai hummus"}', '{"Tosta pane","Spalma hummus"}', NULL, 7, 30, 8, 220);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('orata-patate-verdure', 'Orata al Forno con Patate', 'rest', 'cena', 'media', 35, NULL, '{"pesce","completo"}', '{"200g orata","300g patate","Verdure","20g olio"}', '{"Condisci orata con limone ed erbe","Taglia patate a spicchi","Inforna insieme a 180°C per 30 minuti","Aggiungi verdure"}', NULL, 45, 50, 20, 560);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('tacchino-verdure-pane', 'Tacchino ai Ferri con Verdure', 'rest', 'cena', 'facile', 20, NULL, '{"proteico","veloce"}', '{"250g tacchino","60g pane integrale","Verdure grigliate","20g olio"}', '{"Griglia tacchino","Griglia verdure","Servi con pane"}', NULL, 50, 30, 20, 500);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('minestrone-verdure-patate', 'Minestrone di Verdure con Patate', 'rest', 'cena', 'media', 35, NULL, '{"vegetariano","comfort"}', '{"Verdure miste abbondanti","200g patate","100g hummus (come fonte proteica)","20g olio"}', '{"Taglia verdure e patate","Cuoci in brodo 25 minuti","Servi con hummus a parte","Condisci con olio"}', NULL, 12, 45, 20, 400);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('vellutata-patate-zucca-vitello', 'Vellutata di Patate e Zucca con Vitello', 'rest', 'cena', 'media', 40, NULL, '{"comfort","completo"}', '{"250g vitello","200g zucca","100g patate","Brodo","20g olio"}', '{"Cuoci zucca e patate in brodo","Frulla per ottenere vellutata","Cuoci vitello in padella","Servi insieme"}', NULL, 48, 35, 20, 520);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pollo-insalata-riposo', 'Pollo Grigliato con Insalata Mista', 'rest', 'cena', 'facile', 20, NULL, '{"leggero","proteico"}', '{"250g pollo","Insalata mista abbondante","60g pane","20g olio"}', '{"Griglia pollo","Prepara insalata","Condisci con olio","Servi con pane"}', NULL, 52, 32, 20, 520);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('salmone-verdure-riposo', 'Salmone al Forno con Verdure', 'rest', 'cena', 'facile', 25, NULL, '{"pesce","completo"}', '{"200g salmone","Verdure miste","60g pane","20g olio"}', '{"Condisci salmone","Disponi verdure in teglia","Inforna 20 minuti a 180°C","Servi con pane"}', NULL, 44, 32, 24, 520);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('frittata-verdure-insalata', 'Frittata di Verdure con Insalata', 'rest', 'cena', 'facile', 15, NULL, '{"vegetariano","veloce"}', '{"2 uova + 150g albume","Zucchine, peperoni","Insalata","60g pane","Olio"}', '{"Salta verdure","Prepara frittata","Servi con insalata e pane"}', NULL, 40, 34, 18, 460);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('pesce-vapore-patate', 'Pesce al Vapore con Patate', 'rest', 'cena', 'facile', 25, NULL, '{"leggero","pesce"}', '{"250g pesce bianco","200g patate","Verdure al vapore","20g olio"}', '{"Cuoci pesce al vapore","Cuoci patate","Cuoci verdure al vapore","Condisci con olio e limone"}', NULL, 48, 42, 20, 540);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('hamburger-manzo-verdure', 'Hamburger di Manzo con Verdure', 'rest', 'cena', 'media', 25, NULL, '{"proteico"}', '{"200g manzo magro macinato","1 panino integrale (60g)","Verdure grigliate","Insalata"}', '{"Forma hamburger","Griglia 5-6 minuti per lato","Griglia verdure","Componi burger"}', NULL, 46, 34, 20, 510);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('spiedini-pollo-verdure', 'Spiedini di Pollo e Verdure', 'rest', 'cena', 'media', 25, NULL, '{"proteico","completo"}', '{"250g pollo a cubetti","Peperoni, zucchine, cipolle","60g pane","20g olio"}', '{"Prepara spiedini alternando pollo e verdure","Griglia o cuoci in forno","Servi con pane"}', NULL, 50, 32, 20, 510);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('tonno-insalata-patate', 'Tonno con Insalata e Patate', 'rest', 'cena', 'facile', 25, NULL, '{"completo","veloce"}', '{"200g tonno al naturale","200g patate lesse","Insalata mista","20g olio"}', '{"Lessa patate","Prepara insalata","Sgocciola tonno","Componi piatto e condisci"}', NULL, 42, 40, 20, 510);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('ricotta-verdure-pane', 'Ricotta con Verdure e Pane', 'rest', 'cena', 'facile', 15, NULL, '{"vegetariano","leggero"}', '{"125g ricotta magra","Verdure grigliate abbondanti","60g pane","20g olio"}', '{"Griglia verdure","Servi ricotta con verdure","Accompagna con pane","Condisci con olio"}', NULL, 20, 36, 22, 420);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('branzino-verdure', 'Branzino al Forno con Verdure', 'rest', 'cena', 'media', 35, NULL, '{"pesce","completo"}', '{"250g branzino","Verdure miste","60g pane","20g olio"}', '{"Pulisci branzino","Disponi con verdure in teglia","Inforna 30 minuti","Servi con pane"}', NULL, 48, 32, 20, 500);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('polpette-verdure-sugo', 'Polpette al Sugo con Verdure', 'rest', 'cena', 'media', 30, NULL, '{"proteico","comfort"}', '{"200g carne macinata magra","Salsa pomodoro","Verdure","60g pane"}', '{"Prepara polpette","Cuoci in salsa di pomodoro","Prepara verdure","Servi con pane"}', NULL, 44, 36, 20, 510);

INSERT INTO public.recipes (slug, name, day_type, meal_slot, difficulty, prep_time, category, tags, ingredients, steps, tips, protein_grams, carbs_grams, fats_grams, calories) VALUES ('uova-verdure-pane-riposo', 'Uova con Verdure e Pane', 'rest', 'cena', 'facile', 15, NULL, '{"veloce","proteico"}', '{"2 uova + 150g albume","Verdure miste","60g pane","20g olio"}', '{"Salta verdure","Prepara uova (strapazzate o al tegamino)","Servi con pane"}', NULL, 42, 34, 20, 490);
